config/routes.rb
Rails.application.routes.draw do

  

  
      resources :rapid_share_files	
      resources :users do
      	collection do
	   get 'register'
	   post 'login'
	   get 'logout'
	end
      end	   	

end

app/models/rapid_share_file.rb
class RapidShareFile < ActiveRecord::Base
      has_one :user
      validates :file, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
      validates :username, presence: true, length: {minimum: 4}
      validates :password, presence: true
      validates_confirmation_of :password, message: "Both the pass should match"
      validates :salt, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  before_action :require_login
  
	def require_login
	    if session[:current_user_id].blank?
	    	   flash[:error] = "You must be logged in to access this section"
		   redirect_to users_path
            end
	end    		   
end

app/controllers/rapid_share_files_controller.rb
class RapidShareFilesController < ApplicationController
      
      skip_before_filter :verify_authenticity_key, :only => [:index, :create] 
      
      def index
      	  @all_files = RapidShareFile.where("user_id = ?", session[:current_user_id] )
      end

      def new
      end
      
      def show
      	  @current_file = RapidShareFile.find(params[:id])
	  if @current_file.user_id==session[:current_user_id]
	     send_data @current_file.file, filename: @current_file.title
	  else
             flash[:error] = "You are not authenticated to perform this action."		   
	  end
      end

      def create
      	  if !params.has_key?(:file)
	     flash[:error] = "Please select a file"
	     redirect_to action: "index"
	  else	
	  	new_file = RapidShareFile.new
	  	new_file.title = params[:file].original_filename
	  	new_file.file = params[:file].read
		new_file.user_id = session[:current_user_id]
	  	if new_file.save
		   flash[:notice] = "Your file has been saved successfully!"
		   redirect_to action: "index"
		else
		   flash[:error] = "There was a problem submitting your attachment. Please try again."
		   redirect_to action: "index"
		end  	
          end
      end
      
      def destroy
      	  @file = RapidShareFile.find(params[:id])
	  if @file.user_id==session[:current_user_id]
	     @file.destroy
	  else
	     flash[:error] = "You are not authenticated to delete this file."   
	  end
	  redirect_to rapid_share_files_url
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

      skip_before_action :require_login, :only => [:register, :create, :index, :login]      

      def index
      end

      def create
      	  user = User.new

	  if params[:password]!=params[:password_confirmation]
	     flash[:error] = "The password entered do not match"
	     redirect_to register_users_path

	  else   
	  	 user.username = params[:username]
       	  	 user.salt = SecureRandom.base64(6)

	  	 user.password = encrypt_password(user.salt, params[:password])
	  	 if user.save
	     	    session[:current_user_id] = user.id
	     	    session[:username] = user.username
	     	    redirect_to rapid_share_files_url
	  	 else
			flash[:error] = user.errors.messages
	     		redirect_to register_users_path  	   
	  	  end
          end		  
      end

      def register
      end

      def login
      	  @user = User.find_by_username(params[:username])
	  if @user.blank?
             flash[:error] = "Inavlid Username"
	     redirect_to users_url
	  elsif @user.password.eql? encrypt_password(@user.salt, params[:password])
              session[:current_user_id] = @user.id
	      session[:username] = @user.username			 
	      redirect_to rapid_share_files_url
	  else
	     flash[:error] = "Wrong password"
	     redirect_to users_url    
	  end   			
      end

      def logout
      	  reset_session
	  @@logged_in = false
	  redirect_to users_path
      end

      private

	def encrypt_password(salt, password)
	    pwd = Digest::SHA2.hexdigest(salt + password)
	    return pwd
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/rapid_share_files_helper.rb
module RapidShareFilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rapidshare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
<% flash.delete(name) %>
<% end %>

app/views/rapid_share_files/index.html.erb
<div align="right"
  <h2><%= link_to "Logout", logout_users_path %></h2>
</div>

<div align="left">
  Logged in as <%= session[:username] %>
</div>

<center>
<h1>Root directory</h1>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
<% flash.delete(name) %>
<% end %>

<h2>Upload File</h2>
<%= form_tag({action: :create}, multipart: true) do %>
   <%= file_field_tag 'file' %> <%= submit_tag("Submit") %>
   <br/><br/>
<% end %>

<% index = 1 %>
<table>
  <% if !@all_files.blank? %>
    <% @all_files.each do |file| %>
      <tr>
        <td><%= index %>. </td>
        <td><%= link_to file.title, rapid_share_file_path(file) %></td>
        <td><%= link_to "Delete", rapid_share_file_path(file), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% index+=1 %>
      </tr>
    <% end %>
  <% else %>
     "You haven't uploaded any files yet."
  <% end %>  
</table>
</center>

app/views/rapid_share_files/new.html.erb
<h3>Select a file to upload</h3>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "alert alert-info" %>
  <% flash.delete(name) %>
<% end %><br/>
<%= form_tag({action: :create}, multipart: true) do %>
   <%= file_field_tag 'file' %>
   <br/><br/>
   <%= submit_tag("Submit") %>
<% end %>

app/views/users/index.html.erb
<h1>Login</h1>

<%= render 'messages/message' %>

<%= form_tag({action: :login}) do %>

  <%= label_tag 'Username: ' %><br>
  <%= text_field_tag :username %><br><br>

  <%= label_tag 'Password: ' %><br>
  <%= password_field_tag :password %><br><br>

  <%= submit_tag 'Login' %><br><br>
<% end %>

<%= link_to "New User? Register here", register_users_path %>

app/views/users/register.html.erb
<h1>Please enter the following details to register</h1>
<%= render 'messages/message' %>

<%= form_tag({action: :create}) do %>

  <%= label_tag 'Username: ' %><br>
  <%= text_field_tag :username %><br><br>

  <%= label_tag 'Password: ' %><br>
  <%= password_field_tag :password %><br><br>

  <%= label_tag 'Confirm Password: ' %><br>
  <%= password_field_tag :password_confirmation %><br><br>

  <%= submit_tag 'Login' %><br><br>
<% end %>

app/views/users/show.html.erb
<% index = 1 %>
<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= index %>. </td>
      <td><%= user.username %></td>
      <td><%= user.password %></td>
      <% index+=1 %>
    </tr>
  <% end %>
</table>